### ISSUE TITLE
Blogging

### ISSUE THREAD

**Issue by WhatTheFunnn** [learn-co-curriculum/phase-1-maintaining-a-blog#6]
Just wanted to let you know that the link for https://medium.com/@sherriously/switching-from-standard-bcrypt-rails-authentication-to-devise-1fd0e910bdda#.fj8ckgksqf. Which is the devise for gem. Is no longer a valid article and should be removed or replaced from the curriculum as the medium article loads a 404

**Comment by lizbur10** [comment]
Thank you for bringing this to our attention @WhatTheFunnn ! The broken link has been replaced. Note that you may not see the change in your Canvas course, but it will be there for students moving forward.

Thanks for contributing to the Flatiron School curriculum 💙
